modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "tpmanager"
version = "${version}"
displayName = "Tp Manager"
authors = "Edujos"
description = "Graphical Administrator Interface to manage users' teleportation"
#logoFile = ""

[[dependencies.tpmanager]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tpmanager]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tpmanager]]
modId = "architectury"
type = "required"
versionRange = "[15.0.3,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "tpmanager.mixins.json"
